local:
  data_path: data/
  model_path: model/lda/persistence/lda_model
  dict_path: model/lda/persistence/dict
  index_path: search_engine/lda/persistence/index
  url_path: search_engine/lda/persistence/url
  max_workers: 4
  topics: 40
  passes: 20

zeus_rob:
  data_path: /mnt/auto/people/plgwciro/mors/data/
  model_path: /mnt/auto/people/plgwciro/mors/model/lda/persistence/lda_model
  dict_path: /mnt/auto/people/plgwciro/mors/model/lda/persistence/dict
  index_path: /mnt/auto/people/plgwciro/mors/search_engine/lda/persistence/index
  url_path: /mnt/auto/people/plgwciro/mors/search_engine/lda/persistence/url
  max_workers: 5
  topics: 500
  passes: 20